--------------------------------------------------------
--  파일이 생성됨 - 화요일-8월-08-2023   
--------------------------------------------------------
DROP TABLE "DOG"."BOOK_TBL" cascade constraints;
DROP TABLE "DOG"."MEMBER_TBL" cascade constraints;
DROP TABLE "DOG"."POST_TBL" cascade constraints;
--------------------------------------------------------
--  DDL for Table BOOK_TBL
--------------------------------------------------------

  CREATE TABLE "DOG"."BOOK_TBL" 
   (	"BOOK_USER_NAME" VARCHAR2(30 BYTE), 
	"BOOK_USER_PHONE" VARCHAR2(11 BYTE), 
	"BOOK_POINT" VARCHAR2(12 BYTE), 
	"BOOK_DATE" DATE, 
	"BOOK_TIME" VARCHAR2(15 BYTE), 
	"BOOK_CONCERN" VARCHAR2(100 BYTE), 
	"BOOK_USER_HOUSE" VARCHAR2(100 BYTE), 
	"BOOK_USER_HOUSEHOLD" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEMBER_TBL
--------------------------------------------------------

  CREATE TABLE "DOG"."MEMBER_TBL" 
   (	"MEMBER_EMAIL" VARCHAR2(50 BYTE), 
	"MEMBER_PW" VARCHAR2(30 BYTE), 
	"MEMBER_NAME" VARCHAR2(30 BYTE), 
	"MEMBER_PHONE" VARCHAR2(11 BYTE), 
	"MEMBER_DATE" TIMESTAMP (6) DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table POST_TBL
--------------------------------------------------------

  CREATE TABLE "DOG"."POST_TBL" 
   (	"POST_NO" NUMBER, 
	"POST_TITLE" VARCHAR2(50 BYTE), 
	"POST_CONTENT" VARCHAR2(1000 BYTE), 
	"POST_WRITER" VARCHAR2(50 BYTE), 
	"POST_LIKE" NUMBER, 
	"POST_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_DATE" DATE DEFAULT SYSDATE, 
	"VIEW_COUNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into DOG.BOOK_TBL
SET DEFINE OFF;
REM INSERTING into DOG.MEMBER_TBL
SET DEFINE OFF;
Insert into DOG.MEMBER_TBL (MEMBER_EMAIL,MEMBER_PW,MEMBER_NAME,MEMBER_PHONE,MEMBER_DATE) values ('khuser01@kh.com','55','일일용자','01059595959',to_timestamp('23/08/01 16:50:21.000000000','RR/MM/DD HH24:MI:SSXFF'));
REM INSERTING into DOG.POST_TBL
SET DEFINE OFF;
Insert into DOG.POST_TBL (POST_NO,POST_TITLE,POST_CONTENT,POST_WRITER,POST_LIKE,POST_DATE,UPDATE_DATE,VIEW_COUNT) values (1,'2개월 된 귀요미아콩이입니다','1','관리자',10,to_date('23/08/02','RR/MM/DD'),to_date('23/08/02','RR/MM/DD'),0);
Insert into DOG.POST_TBL (POST_NO,POST_TITLE,POST_CONTENT,POST_WRITER,POST_LIKE,POST_DATE,UPDATE_DATE,VIEW_COUNT) values (2,'사랑한지 2년째!','1','관리자',10,to_date('23/08/02','RR/MM/DD'),to_date('23/08/02','RR/MM/DD'),0);
Insert into DOG.POST_TBL (POST_NO,POST_TITLE,POST_CONTENT,POST_WRITER,POST_LIKE,POST_DATE,UPDATE_DATE,VIEW_COUNT) values (3,'이지(다롱) 입양 후기','1','관리자',10,to_date('23/08/02','RR/MM/DD'),to_date('23/08/02','RR/MM/DD'),0);
Insert into DOG.POST_TBL (POST_NO,POST_TITLE,POST_CONTENT,POST_WRITER,POST_LIKE,POST_DATE,UPDATE_DATE,VIEW_COUNT) values (4,'새로운 가족♡','1','관리자',10,to_date('23/08/02','RR/MM/DD'),to_date('23/08/02','RR/MM/DD'),0);
Insert into DOG.POST_TBL (POST_NO,POST_TITLE,POST_CONTENT,POST_WRITER,POST_LIKE,POST_DATE,UPDATE_DATE,VIEW_COUNT) values (5,'보리 입양 후기♥','1','관리자',10,to_date('23/08/02','RR/MM/DD'),to_date('23/08/02','RR/MM/DD'),0);
Insert into DOG.POST_TBL (POST_NO,POST_TITLE,POST_CONTENT,POST_WRITER,POST_LIKE,POST_DATE,UPDATE_DATE,VIEW_COUNT) values (6,'콩떡이 입양 100일 되는 날이에요♥','1','관리자',10,to_date('23/08/02','RR/MM/DD'),to_date('23/08/02','RR/MM/DD'),0);
Insert into DOG.POST_TBL (POST_NO,POST_TITLE,POST_CONTENT,POST_WRITER,POST_LIKE,POST_DATE,UPDATE_DATE,VIEW_COUNT) values (7,'이꼬순','1','관리자',10,to_date('23/08/02','RR/MM/DD'),to_date('23/08/02','RR/MM/DD'),0);
Insert into DOG.POST_TBL (POST_NO,POST_TITLE,POST_CONTENT,POST_WRITER,POST_LIKE,POST_DATE,UPDATE_DATE,VIEW_COUNT) values (8,'자루 입양 후기','1','관리자',10,to_date('23/08/02','RR/MM/DD'),to_date('23/08/02','RR/MM/DD'),0);
Insert into DOG.POST_TBL (POST_NO,POST_TITLE,POST_CONTENT,POST_WRITER,POST_LIKE,POST_DATE,UPDATE_DATE,VIEW_COUNT) values (9,'구름이','1','관리자',10,to_date('23/08/02','RR/MM/DD'),to_date('23/08/02','RR/MM/DD'),0);
Insert into DOG.POST_TBL (POST_NO,POST_TITLE,POST_CONTENT,POST_WRITER,POST_LIKE,POST_DATE,UPDATE_DATE,VIEW_COUNT) values (10,'빵이','1','관리자',1,to_date('23/08/02','RR/MM/DD'),to_date('23/08/02','RR/MM/DD'),0);
Insert into DOG.POST_TBL (POST_NO,POST_TITLE,POST_CONTENT,POST_WRITER,POST_LIKE,POST_DATE,UPDATE_DATE,VIEW_COUNT) values (11,'말랑이','1','관리자',1,to_date('23/08/02','RR/MM/DD'),to_date('23/08/02','RR/MM/DD'),0);
Insert into DOG.POST_TBL (POST_NO,POST_TITLE,POST_CONTENT,POST_WRITER,POST_LIKE,POST_DATE,UPDATE_DATE,VIEW_COUNT) values (12,'꼬질이','1','관리자',1,to_date('23/08/02','RR/MM/DD'),to_date('23/08/02','RR/MM/DD'),0);
Insert into DOG.POST_TBL (POST_NO,POST_TITLE,POST_CONTENT,POST_WRITER,POST_LIKE,POST_DATE,UPDATE_DATE,VIEW_COUNT) values (13,'구름이','1','관리자',1,to_date('23/08/02','RR/MM/DD'),to_date('23/08/02','RR/MM/DD'),0);
Insert into DOG.POST_TBL (POST_NO,POST_TITLE,POST_CONTENT,POST_WRITER,POST_LIKE,POST_DATE,UPDATE_DATE,VIEW_COUNT) values (14,'뭉치','1','관리자',11,to_date('23/08/02','RR/MM/DD'),to_date('23/08/02','RR/MM/DD'),0);
Insert into DOG.POST_TBL (POST_NO,POST_TITLE,POST_CONTENT,POST_WRITER,POST_LIKE,POST_DATE,UPDATE_DATE,VIEW_COUNT) values (15,'빠빵이','1','관리자',1,to_date('23/08/02','RR/MM/DD'),to_date('23/08/02','RR/MM/DD'),0);
Insert into DOG.POST_TBL (POST_NO,POST_TITLE,POST_CONTENT,POST_WRITER,POST_LIKE,POST_DATE,UPDATE_DATE,VIEW_COUNT) values (16,'구름이','1','관리자',11,to_date('23/08/02','RR/MM/DD'),to_date('23/08/02','RR/MM/DD'),0);
--------------------------------------------------------
--  DDL for Index SYS_C007251
--------------------------------------------------------

  CREATE UNIQUE INDEX "DOG"."SYS_C007251" ON "DOG"."MEMBER_TBL" ("MEMBER_EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007279
--------------------------------------------------------

  CREATE UNIQUE INDEX "DOG"."SYS_C007279" ON "DOG"."POST_TBL" ("POST_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BOOK_TBL
--------------------------------------------------------

  ALTER TABLE "DOG"."BOOK_TBL" MODIFY ("BOOK_USER_HOUSEHOLD" NOT NULL ENABLE);
  ALTER TABLE "DOG"."BOOK_TBL" MODIFY ("BOOK_USER_HOUSE" NOT NULL ENABLE);
  ALTER TABLE "DOG"."BOOK_TBL" MODIFY ("BOOK_CONCERN" NOT NULL ENABLE);
  ALTER TABLE "DOG"."BOOK_TBL" MODIFY ("BOOK_TIME" NOT NULL ENABLE);
  ALTER TABLE "DOG"."BOOK_TBL" MODIFY ("BOOK_DATE" NOT NULL ENABLE);
  ALTER TABLE "DOG"."BOOK_TBL" MODIFY ("BOOK_POINT" NOT NULL ENABLE);
  ALTER TABLE "DOG"."BOOK_TBL" MODIFY ("BOOK_USER_PHONE" NOT NULL ENABLE);
  ALTER TABLE "DOG"."BOOK_TBL" MODIFY ("BOOK_USER_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER_TBL
--------------------------------------------------------

  ALTER TABLE "DOG"."MEMBER_TBL" ADD PRIMARY KEY ("MEMBER_EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DOG"."MEMBER_TBL" MODIFY ("MEMBER_PHONE" NOT NULL ENABLE);
  ALTER TABLE "DOG"."MEMBER_TBL" MODIFY ("MEMBER_NAME" NOT NULL ENABLE);
  ALTER TABLE "DOG"."MEMBER_TBL" MODIFY ("MEMBER_PW" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POST_TBL
--------------------------------------------------------

  ALTER TABLE "DOG"."POST_TBL" ADD PRIMARY KEY ("POST_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DOG"."POST_TBL" MODIFY ("POST_WRITER" NOT NULL ENABLE);
  ALTER TABLE "DOG"."POST_TBL" MODIFY ("POST_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "DOG"."POST_TBL" MODIFY ("POST_TITLE" NOT NULL ENABLE);

commit;